const DOMAINS = [
      {id:'cardio', title:'Capacidad cardiorrespiratoria', short:'Cardiorrespiratoria', icon:'pulse', subtitle:'Cómo responde al esfuerzo.', definition:'Capacidad de los sistemas circulatorio y respiratorio para aportar oxígeno durante una actividad sostenida.', test:'Pruebas de campo o submáximas validadas según la población; la caminata de 6 minutos informa sobre capacidad funcional. El análisis de gases en una prueba cardiopulmonar permite medir el consumo de oxígeno.', limit:'La distancia caminada no es una medida directa del VO₂máx. El protocolo, los síntomas, la frecuencia cardiaca y el esfuerzo percibido ayudan a interpretar la respuesta.', link:'Orienta intensidad, tiempo, tipo de actividad aeróbica y progresión.'},
      {id:'body', title:'Composición corporal', short:'Composición corporal', icon:'body', subtitle:'Más que un número en la balanza.', definition:'Distribución de componentes corporales, como masa grasa y masa libre de grasa. No equivale únicamente al peso.', test:'Pliegues cutáneos o bioimpedancia con técnica, ecuaciones y condiciones apropiadas; DXA si es pertinente y está disponible. Peso, talla y cintura aportan contexto antropométrico.', limit:'El IMC no diferencia músculo y grasa. La bioimpedancia estima componentes y depende, entre otros factores, de hidratación y ecuaciones. La cintura no mide por sí sola toda la composición.', link:'Apoya objetivos realistas y seguimiento; no determina por sí sola la dosis de ejercicio.'},
      {id:'strength', title:'Fuerza muscular', short:'Fuerza', icon:'strength', subtitle:'Cuánta fuerza puede producir.', definition:'Capacidad de generar tensión o fuerza en una acción muscular. Es distinta de sostener o repetir esfuerzos: eso es resistencia muscular.', test:'Dinamometría de prensión para fuerza de la mano; pruebas de fuerza de otros grupos o cargas submáximas con técnica y supervisión, según seguridad y propósito.', limit:'La prensión no representa toda la fuerza corporal. Una 1RM no es la primera opción automática en una persona sin experiencia; requiere preparación, protocolo y condiciones apropiadas.', link:'Orienta cargas, selección de ejercicios, volumen y progresión del trabajo de fuerza.'},
      {id:'flex', title:'Flexibilidad', short:'Flexibilidad', icon:'flex', subtitle:'El rango de movimiento importa.', definition:'Capacidad de movimiento en una articulación o conjunto de articulaciones, influida por tejidos y condiciones específicas.', test:'Goniometría del rango articular; sit-and-reach como prueba de campo con alcance y limitaciones específicos. Registrar lado, postura, dolor y protocolo.', limit:'Una sola prueba no resume todas las articulaciones. El dolor no es una meta del estiramiento: exige interpretar y adaptar la evaluación.', link:'Orienta tipo de ejercicios de movilidad o estiramiento, rangos tolerados y progresión.'}
    ];
    const FITT = [
      {id:'F',letter:'F',name:'Frecuencia',meaning:'Cuántos días o sesiones por semana.'},
      {id:'I',letter:'I',name:'Intensidad',meaning:'Qué tan exigente es el esfuerzo.'},
      {id:'T1',letter:'T',name:'Tiempo',meaning:'Cuánto dura cada sesión o esfuerzo.'},
      {id:'T2',letter:'T',name:'Tipo',meaning:'Qué modalidad de ejercicio se realiza.'},
      {id:'V',letter:'V',name:'Volumen',meaning:'Cantidad total de ejercicio acumulado.'},
      {id:'P',letter:'P',name:'Progresión',meaning:'Cómo se ajusta la dosis a lo largo del tiempo.'}
    ];
    function atlasCard(d) { return `<article class="atlas-item"><h3>${icon(d.icon)} ${d.title}</h3><p><strong>Qué evalúa.</strong> ${d.definition}</p><p><strong>Ejemplos.</strong> ${d.test}</p><p><strong>Qué no debes concluir.</strong> ${d.limit}</p><p><strong>Puente con FITT-VP.</strong> ${d.link}</p></article>`; }
    function openAtlas(domain) {
      const ordered=domain?[...DOMAINS.filter(d=>d.id===domain),...DOMAINS.filter(d=>d.id!==domain)]:DOMAINS;
      showModal('Fichas de consulta',`<p class="muted">Consulta libre durante el juego. Lo importante no es memorizar una prueba, sino entender su utilidad y sus límites.</p>${ordered.map(atlasCard).join('')}<article class="atlas-item"><h3>Otros componentes</h3><p>Resistencia muscular, equilibrio, coordinación, potencia y desempeño funcional pueden añadirse según la persona. Estos cuatro núcleos no agotan toda la evaluación de la condición física.</p><p>Antes de aplicar cualquier prueba: cribado, consentimiento, protocolo válido, preparación, equipo apropiado y criterios de seguridad. La indicación de valoración médica depende del caso.</p></article><article class="atlas-item"><h3>FITT-VP en seis preguntas</h3>${FITT.map(f=>`<p><strong>${f.name}:</strong> ${f.meaning}</p>`).join('')}<p>Volumen: cantidad total acumulada, por ejemplo minutos/semana en ejercicio aeróbico o series × repeticiones y carga en fuerza, según el propósito.</p></article><h3>Fuentes de fundamento</h3><p class="source">AHA (revisión 2024). <a href="https://www.heart.org/en/health-topics/consumer-healthcare/medication-information/how-do-beta-blocker-drugs-affect-exercise" target="_blank" rel="noopener noreferrer">Betabloqueadores y ejercicio</a>: la medicación puede modificar la respuesta de la frecuencia cardiaca; no cambiar medicamentos por cuenta propia.</p><p class="source">ACSM. <a href="https://books.google.com/books/about/ACSM_s_Health_Related_Physical_Fitness_A.html?id=ZPo96rd3PpAC" target="_blank" rel="noopener noreferrer">Health-Related Physical Fitness Assessment Manual, 4.ª ed. (2013)</a>. Distingue composición corporal, fuerza, resistencia muscular, flexibilidad y capacidad cardiorrespiratoria.</p><p class="source">Garber et al. <a href="https://pubmed.ncbi.nlm.nih.gov/21694556/" target="_blank" rel="noopener noreferrer">ACSM Position Stand: Quantity and Quality of Exercise… (2011)</a>. DOI: 10.1249/MSS.0b013e318213fefb. Fundamento de individualización y de la estructura de prescripción; no se presenta como la última edición de una guía.</p><p class="tiny muted">Son fuentes de fundamento general, no protocolos completos de administración de cada prueba. La clase debe complementarse con manuales vigentes y criterios profesionales. Solo los enlaces a fuentes requieren conexión a internet.</p>`);
    }
